DROP SCHEMA IF EXISTS public CASCADE;
DROP OWNED BY cuttable_api;
DROP USER IF EXISTS cuttable_api;

CREATE SCHEMA public;

/* TABLES */
CREATE TABLE public.account (
  id       SERIAL PRIMARY KEY,
  email    VARCHAR(255) UNIQUE,
  password VARCHAR(60)
);

/* CREATE USERS, REVOKE AND GRANT PRIVILEGES */
CREATE USER cuttable_api WITH PASSWORD '@pxQTpSX$Ymsk#^0';
REVOKE CONNECT ON DATABASE cuttable FROM PUBLIC;
GRANT CONNECT ON DATABASE cuttable TO cuttable_api;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO cuttable_api;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PUBLIC TO cuttable_api;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO cuttable_api;